# Generated by Django 6.0.7 on 2026-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Например: Nike, Adidas, Loro Piana', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Например: черный, белый, красный', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, help_text='Например: хлопок 50%, полиэстер 50%', max_length=255, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс')], default='U', max_length=1, verbose_name='Пол'),
        ),
    ]
