# Generated by Django 6.0.7 on 2026-09-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('cdek', 'СДЭК'), ('boxberry', 'Boxberry'), ('post', 'Почта России'), ('yandex', 'Яндекс.Доставка'), ('dellin', 'Деловые Линии'), ('other', 'Другая')], max_length=20, verbose_name='Транспортная компания')),
                ('name', models.CharField(max_length=200, verbose_name='Название пункта')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('work_time', models.CharField(blank=True, max_length=200, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
                'ordering': ['carrier', 'city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.pickuppoint', verbose_name='Пункт выдачи'),
        ),
    ]
